/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm_proje;


    import java.sql.*;
    import javax.swing.JOptionPane;

/**
 *
 * @author gacar
 */
public class admin extends javax.swing.JFrame {
    int mousepX;
    int mousepY;

    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ana_panel = new javax.swing.JPanel();
        lbl_sinego = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        lbl_sineoto1 = new javax.swing.JLabel();
        lbl_sineoto2 = new javax.swing.JLabel();
        lbl_sinego1 = new javax.swing.JLabel();
        lbl_sineoto3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ana_panel.setBackground(new java.awt.Color(34, 38, 41));
        ana_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ana_panelMouseDragged(evt);
            }
        });
        ana_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ana_panelMousePressed(evt);
            }
        });

        lbl_sinego.setFont(new java.awt.Font("Bebas Neue Bold", 1, 48)); // NOI18N
        lbl_sinego.setForeground(new java.awt.Color(69, 162, 158));
        lbl_sinego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sinego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_lock.png"))); // NOI18N

        lbl_exit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(197, 198, 199));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(34, 38, 41));
        jTextField1.setForeground(new java.awt.Color(197, 198, 199));

        btn_giris.setBackground(new java.awt.Color(134, 194, 50));
        btn_giris.setForeground(new java.awt.Color(34, 38, 41));
        btn_giris.setText("Giriş");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        lbl_sineoto1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbl_sineoto1.setForeground(new java.awt.Color(197, 198, 199));
        lbl_sineoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sineoto1.setText("Kullanıcı Adı");

        lbl_sineoto2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbl_sineoto2.setForeground(new java.awt.Color(197, 198, 199));
        lbl_sineoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sineoto2.setText("Şifre");

        lbl_sinego1.setFont(new java.awt.Font("Elemental End", 0, 14)); // NOI18N
        lbl_sinego1.setForeground(new java.awt.Color(134, 194, 50));
        lbl_sinego1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sinego1.setText("SİNE GO");

        lbl_sineoto3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lbl_sineoto3.setForeground(new java.awt.Color(97, 137, 47));
        lbl_sineoto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sineoto3.setText("Admin Giriş");

        jTextField2.setBackground(new java.awt.Color(34, 38, 41));
        jTextField2.setForeground(new java.awt.Color(197, 198, 199));

        javax.swing.GroupLayout ana_panelLayout = new javax.swing.GroupLayout(ana_panel);
        ana_panel.setLayout(ana_panelLayout);
        ana_panelLayout.setHorizontalGroup(
            ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ana_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ana_panelLayout.createSequentialGroup()
                .addGroup(ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ana_panelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_sinego1)
                            .addComponent(lbl_sineoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(lbl_sinego))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ana_panelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_sineoto2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(btn_giris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(lbl_sineoto1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 90, Short.MAX_VALUE))
        );
        ana_panelLayout.setVerticalGroup(
            ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ana_panelLayout.createSequentialGroup()
                .addGroup(ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ana_panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ana_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_sinego, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ana_panelLayout.createSequentialGroup()
                                .addComponent(lbl_sineoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_sinego1)))))
                .addGap(37, 37, 37)
                .addComponent(lbl_sineoto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_sineoto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ana_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ana_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;user=sa;password=123;databaseName=sineDB;";
            
            
            Connection con = DriverManager.getConnection(url);
            String sql = "SELECT * FROM admin WHERE kulad=? AND sifre=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null,"giriş başarılı");
            panel pnl = new panel();
            this.setVisible(false);
            pnl.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"kullanıcı adı veya şifre hatalı!");

            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }//GEN-LAST:event_btn_girisActionPerformed

    private void ana_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ana_panelMousePressed
                mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_ana_panelMousePressed

    private void ana_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ana_panelMouseDragged
                     int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX-mousepX,kordinatY-mousepY);
        //System.out.println(kordinatX+","+kordinatY);
    }//GEN-LAST:event_ana_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ana_panel;
    private javax.swing.JButton btn_giris;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_sinego;
    private javax.swing.JLabel lbl_sinego1;
    private javax.swing.JLabel lbl_sineoto1;
    private javax.swing.JLabel lbl_sineoto2;
    private javax.swing.JLabel lbl_sineoto3;
    // End of variables declaration//GEN-END:variables
}
