package sm_proje;

public class ana extends javax.swing.JFrame {
    int mousepX;
    int mousepY;

    public ana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sag_panel = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        cinema_image = new javax.swing.JLabel();
        user_image1 = new javax.swing.JLabel();
        lbl_sineoto1 = new javax.swing.JLabel();
        lbl_sineoto2 = new javax.swing.JLabel();
        panel_sol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 38, 41));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(34, 38, 41));
        jPanel1.setForeground(new java.awt.Color(197, 198, 199));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        sag_panel.setBackground(new java.awt.Color(34, 38, 41));

        lbl_exit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(197, 198, 199));
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        cinema_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clapperboard.png"))); // NOI18N
        cinema_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinema_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinema_imageMouseClicked(evt);
            }
        });

        user_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        user_image1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user_image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_image1MouseClicked(evt);
            }
        });

        lbl_sineoto1.setForeground(new java.awt.Color(197, 198, 199));
        lbl_sineoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sineoto1.setText("Admin Girişi");

        lbl_sineoto2.setForeground(new java.awt.Color(197, 198, 199));
        lbl_sineoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sineoto2.setText("Sinemalar");

        javax.swing.GroupLayout sag_panelLayout = new javax.swing.GroupLayout(sag_panel);
        sag_panel.setLayout(sag_panelLayout);
        sag_panelLayout.setHorizontalGroup(
            sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sag_panelLayout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sag_panelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_image1)
                    .addComponent(lbl_sineoto1))
                .addGap(62, 62, 62)
                .addGroup(sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cinema_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sineoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sag_panelLayout.setVerticalGroup(
            sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sag_panelLayout.createSequentialGroup()
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cinema_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_image1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sag_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sineoto1)
                    .addComponent(lbl_sineoto2))
                .addGap(112, 112, 112))
        );

        panel_sol.setBackground(new java.awt.Color(11, 12, 16));
        panel_sol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ana.png"))); // NOI18N
        panel_sol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_sol.setFocusable(false);
        panel_sol.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_solMouseDragged(evt);
            }
        });
        panel_sol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_solMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_sol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sag_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_sol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sag_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void panel_solMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_solMousePressed
         mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_panel_solMousePressed

    private void panel_solMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_solMouseDragged
              int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX-mousepX,kordinatY-mousepY);
        //System.out.println(kordinatX+","+kordinatY);
    }//GEN-LAST:event_panel_solMouseDragged

    private void user_image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_image1MouseClicked
      admin adm = new admin();
      this.setVisible(false);
      adm.setVisible(true);
    }//GEN-LAST:event_user_image1MouseClicked

    private void cinema_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinema_imageMouseClicked
       sinemalar snm = new sinemalar();
       this.setVisible(false);
       snm.setVisible(true);      
    }//GEN-LAST:event_cinema_imageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinema_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_sineoto1;
    private javax.swing.JLabel lbl_sineoto2;
    private javax.swing.JLabel panel_sol;
    private javax.swing.JPanel sag_panel;
    private javax.swing.JLabel user_image1;
    // End of variables declaration//GEN-END:variables
}
